In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
df=pd.read_csv('cleaned_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       3276 non-null   int64  
 1   ph               3276 non-null   float64
 2   Hardness         3276 non-null   float64
 3   Solids           3276 non-null   float64
 4   Chloramines      3276 non-null   float64
 5   Sulfate          3276 non-null   float64
 6   Conductivity     3276 non-null   float64
 7   Organic_carbon   3276 non-null   float64
 8   Trihalomethanes  3276 non-null   float64
 9   Turbidity        3276 non-null   float64
 10  Potability       3276 non-null   int64  
dtypes: float64(9), int64(2)
memory usage: 281.7 KB


In [3]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

In [4]:
X=df.drop('Potability',axis=1)
y=df['Potability']

In [5]:
X.shape

(3276, 9)

In [6]:
y.shape

(3276,)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [10]:
scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)  


In [11]:
scaled_X_train.shape

(2620, 9)

In [12]:
scaled_X_test.shape

(656, 9)

# Logistic Regression

In [13]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [14]:
model_lr=LogisticRegression(penalty='l1',solver='saga')

In [15]:
model_lr.fit(scaled_X_train,y_train)

LogisticRegression(penalty='l1', solver='saga')

In [16]:
y_pred=model_lr.predict(scaled_X_test)

In [17]:
print(f"accuracy_score:{accuracy_score(y_test,y_pred)}\n ")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred)} ")
print(f"Classification reqort:\n{classification_report(y_test,y_pred)} ")

accuracy_score:0.6280487804878049
 
Confusion matrix:
[[412   0]
 [244   0]] 
Classification reqort:
              precision    recall  f1-score   support

           0       0.63      1.00      0.77       412
           1       0.00      0.00      0.00       244

    accuracy                           0.63       656
   macro avg       0.31      0.50      0.39       656
weighted avg       0.39      0.63      0.48       656
 


c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Decision tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
model_dtree=DecisionTreeClassifier(criterion='gini')

In [20]:
model_dtree.fit(scaled_X_train,y_train)

DecisionTreeClassifier()

In [21]:
y_pred_dt=model_dtree.predict(scaled_X_test)

In [61]:
# Train model
model = DecisionTreeClassifier()
model.fit(scaled_X_train, y_train)

# Train accuracy
train_preds = model.predict(X_train)
train_acc = accuracy_score(y_train, train_preds)

# Test accuracy
test_preds = model.predict(scaled_X_test)
test_acc = accuracy_score(y_test, test_preds)

print(f"Training Accuracy: {train_acc:.2f}")
print(f"Testing Accuracy: {test_acc:.2f}")


Training Accuracy: 0.61
Testing Accuracy: 0.55


c:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


# Let's make the modern more generalize 

In [23]:
print(f"accuracy_score:{np.round(accuracy_score(y_test,y_pred_dt)*100)}%\n ")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred_dt)} ")
print(f"Classification reqort:\n{classification_report(y_test,y_pred_dt)} ")

accuracy_score:57.0%
 
Confusion matrix:
[[259 153]
 [127 117]] 
Classification reqort:
              precision    recall  f1-score   support

           0       0.67      0.63      0.65       412
           1       0.43      0.48      0.46       244

    accuracy                           0.57       656
   macro avg       0.55      0.55      0.55       656
weighted avg       0.58      0.57      0.58       656
 


In [62]:
y_pred_dt_train=model_dtree.predict(X_train)

c:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


In [63]:
print(f"accuracy_score:{np.round(accuracy_score(y_train,y_pred_dt_train)*100)}\n ")
print(f"Confusion matrix:\n{confusion_matrix(y_train,y_pred_dt_train)} ")
print(f"Classification reqort:\n{classification_report(y_train,y_pred_dt_train)} ")

accuracy_score:61.0
 
Confusion matrix:
[[1586    0]
 [1034    0]] 
Classification reqort:
              precision    recall  f1-score   support

           0       0.61      1.00      0.75      1586
           1       0.00      0.00      0.00      1034

    accuracy                           0.61      2620
   macro avg       0.30      0.50      0.38      2620
weighted avg       0.37      0.61      0.46      2620
 


c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Random Forest

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
model_rdtree=RandomForestClassifier(criterion='gini',class_weight='balanced')

In [66]:
model_rdtree.fit(scaled_X_train,y_train)

RandomForestClassifier(class_weight='balanced')

In [67]:
y_pred_train_rd=model_rdtree.predict(X_train)
y_pred_test_rd=model_rdtree.predict(X_test)

c:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [68]:
print(f"accuracy_score:{np.round(accuracy_score(y_train,y_pred_train_rd)*100)}\n ")
print(f"Confusion matrix:\n{confusion_matrix(y_train,y_pred_train_rd)} ")
print(f"Classification reqort:\n{classification_report(y_train,y_pred_train_rd)} ")

accuracy_score:61.0
 
Confusion matrix:
[[1586    0]
 [1034    0]] 
Classification reqort:
              precision    recall  f1-score   support

           0       0.61      1.00      0.75      1586
           1       0.00      0.00      0.00      1034

    accuracy                           0.61      2620
   macro avg       0.30      0.50      0.38      2620
weighted avg       0.37      0.61      0.46      2620
 


c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [31]:
print(f"accuracy_score:{np.round(accuracy_score(y_test,y_pred_test_rd)*100)}%\n ")
print(f"Confusion matrix:\n{confusion_matrix(y_test,y_pred_test_rd)} ")
print(f"Classification reqort:\n{classification_report(y_test,y_pred_test_rd)} ")

accuracy_score:63.0%
 
Confusion matrix:
[[412   0]
 [244   0]] 
Classification reqort:
              precision    recall  f1-score   support

           0       0.63      1.00      0.77       412
           1       0.00      0.00      0.00       244

    accuracy                           0.63       656
   macro avg       0.31      0.50      0.39       656
weighted avg       0.39      0.63      0.48       656
 


c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# K nearest Neighbor KNN

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
#Knn_model=KNeighborsClassifier()

In [84]:
test_acc=[]
train_acc=[]

for i in range(1,20):
    Knn_model=KNeighborsClassifier(n_neighbors=i)
    Knn_model.fit(scaled_X_train,y_train)
    test_acc=Knn_model.predict(scaled_X_test)
    train_acc=Knn_model.predict(scaled_X_train)
    print(f"{i}  test accuracy_score {accuracy_score(y_test,test_acc)}")
    #print(f"{i} Train accuracy_score {accuracy_score(y_train,train_acc)}")


1  test accuracy_score 0.6158536585365854
2  test accuracy_score 0.6585365853658537
3  test accuracy_score 0.6326219512195121
4  test accuracy_score 0.6478658536585366
5  test accuracy_score 0.6280487804878049
6  test accuracy_score 0.6432926829268293
7  test accuracy_score 0.6310975609756098
8  test accuracy_score 0.6371951219512195
9  test accuracy_score 0.6417682926829268
10  test accuracy_score 0.6600609756097561
11  test accuracy_score 0.6539634146341463
12  test accuracy_score 0.6570121951219512
13  test accuracy_score 0.6524390243902439
14  test accuracy_score 0.6600609756097561
15  test accuracy_score 0.6615853658536586
16  test accuracy_score 0.663109756097561
17  test accuracy_score 0.6661585365853658
18  test accuracy_score 0.6646341463414634
19  test accuracy_score 0.6692073170731707


# finalizing the model

In [35]:
Knn_model=KNeighborsClassifier(n_neighbors=19)

In [36]:
Knn_model.fit(scaled_X_train,y_train)

KNeighborsClassifier(n_neighbors=19)

In [37]:
y_pred=Knn_model.predict(scaled_X_test)

In [38]:
print(f" accuracy score:{accuracy_score(y_test,y_pred)*100}")

 accuracy score:66.92073170731707


In [85]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.68      0.89      0.77       412
           1       0.62      0.30      0.40       244

    accuracy                           0.67       656
   macro avg       0.65      0.59      0.59       656
weighted avg       0.66      0.67      0.63       656



# Support Vector Machine(SVM)

In [39]:
from sklearn.svm import SVC

In [74]:
model_svm=SVC(kernel='rbf',random_state=42)

In [75]:
model_svm.fit(scaled_X_train,y_train)

SVC(random_state=42)

In [76]:
pred_svm=model_svm.predict(scaled_X_test)
train_pred_svm=model_svm.predict(scaled_X_train)

In [78]:
print(classification_report(y_test,pred_svm))

              precision    recall  f1-score   support

           0       0.69      0.92      0.79       412
           1       0.70      0.32      0.44       244

    accuracy                           0.70       656
   macro avg       0.70      0.62      0.61       656
weighted avg       0.70      0.70      0.66       656



In [79]:
print(f" accuracy score:{accuracy_score(y_train,train_pred_svm)*100}")

 accuracy score:73.77862595419847


In [80]:
print(f" accuracy score:{accuracy_score(y_test,pred_svm)*100}")

 accuracy score:69.51219512195121


In [46]:
df['Potability'].value_counts(normalize=True)

Potability
0    0.60989
1    0.39011
Name: proportion, dtype: float64

In [71]:
from sklearn.model_selection import GridSearchCV

params = {
    'C': [0.1, 1, 10],
    'gamma': [0.001, 0.01, 0.1, 1],
    'kernel': ['rbf'],
    'class_weight': ['balanced']
}

grid = GridSearchCV(SVC(probability=True), param_grid=params, cv=5, scoring='f1_macro')
grid.fit(X_train, y_train)

best_model = grid.best_estimator_


In [48]:
grid_predictions=grid.predict(scaled_X_test)
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.63      1.00      0.77       412
           1       0.00      0.00      0.00       244

    accuracy                           0.63       656
   macro avg       0.31      0.50      0.39       656
weighted avg       0.39      0.63      0.48       656



c:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\parth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. 

# ADA boost Classifer

In [49]:
from sklearn.ensemble import AdaBoostClassifier

In [50]:
model_ada=AdaBoostClassifier(n_estimators=75,learning_rate=0.03)

In [51]:
model_ada.fit(scaled_X_train,y_train)

c:\Users\parth\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(learning_rate=0.03, n_estimators=75)

In [52]:
pred=model_ada.predict(scaled_X_test)

In [53]:
print(f" accuracy score:{accuracy_score(y_test,pred)*100}")

 accuracy score:63.71951219512195


# XG Boost

In [54]:
from xgboost import XGBClassifier

In [55]:
model_xgb=XGBClassifier(n_estimators=200,learning_rate=0.03)

In [56]:
model_xgb.fit(scaled_X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.03, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [57]:
pred_xgb=model_xgb.predict(scaled_X_test)

In [58]:
print(f"accuracy score:{accuracy_score(y_test,pred_xgb)*100}")

accuracy score:68.14024390243902


In [59]:
train_xgb=model_xgb.predict(scaled_X_train)
print(f"accuracy score:{accuracy_score(y_train,train_xgb)*100}")

accuracy score:83.74045801526717


In [60]:
joblib.dump(model_svm, 'model_svm.pkl')

# Save the scaler (replace scaler with your scaler variable)
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

# Model tuning and Retrain

In [87]:
df = pd.read_csv("cleaned_data.csv")  # or your own dataset

X = df.drop("Potability", axis=1)
y = df["Potability"]


In [88]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [89]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [90]:
from imblearn.over_sampling import SMOTE

In [91]:
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)


In [95]:
count=1

for n_neighbors in range(1,20):

    knn = KNeighborsClassifier(n_neighbors)
    knn.fit(X_train_res, y_train_res)
    y_pred_knn = knn.predict(X_test_scaled)

    print(f"{count}th Times KNN Classification Report:")
    count+=1
    print(classification_report(y_test, y_pred_knn))


1th Times KNN Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.72      0.70       400
           1       0.52      0.47      0.49       256

    accuracy                           0.62       656
   macro avg       0.60      0.60      0.60       656
weighted avg       0.62      0.62      0.62       656

2th Times KNN Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.82      0.72       400
           1       0.50      0.29      0.36       256

    accuracy                           0.61       656
   macro avg       0.57      0.55      0.54       656
weighted avg       0.59      0.61      0.58       656

3th Times KNN Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.65      0.67       400
           1       0.50      0.55      0.52       256

    accuracy                           0.61       656
   macro avg     

In [96]:
svm = SVC(kernel='rbf', probability=True)
svm.fit(X_train_res, y_train_res)
y_pred_svm = svm.predict(X_test_scaled)

print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))


SVM Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.69      0.71       400
           1       0.56      0.61      0.58       256

    accuracy                           0.66       656
   macro avg       0.65      0.65      0.65       656
weighted avg       0.67      0.66      0.66       656



In [108]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(criterion='gini',class_weight='balanced',random_state=42)
rf_model.fit(X_train_res, y_train_res)
print(classification_report(y_test, rf_model.predict(X_test_scaled)))
print(f"Random Forest Accuracy:{accuracy_score(y_test,rf_model.predict(X_test_scaled))}")



              precision    recall  f1-score   support

           0       0.86      0.91      0.88       400
           1       0.84      0.77      0.80       256

    accuracy                           0.85       656
   macro avg       0.85      0.84      0.84       656
weighted avg       0.85      0.85      0.85       656

Random Forest Accuracy:0.8521341463414634


In [110]:
joblib.dump(rf_model, "random_forest_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']